### ISSUE TITLE
Reproduce Code

### ISSUE THREAD

**Issue by MengXu0826** [ltgoslo/definition_modeling#2]
Hi there,

Followed your [Usage](https://github.com/ltgoslo/definition_modeling#usage), I've generated `predicted.npz` and `predicted.tsv.gz`. The dataset I used is Wordnet. But I don't know what to do next. May you provide the completed experimental procedure?

I try to run `cluster_definitions.py` or `sense_label.py`, but both two files need `complete.tsv.gz` containing usages and cluster ids, could you please tell me how to get this?

Thanks!

**Comment by akutuzov** [comment]
Hi!
What exactly is your aim? To produce cluster labels / sense definitions, you first of all need **usage clusters**.
WordNet does not contain any usage clusters. 
If you simply want to generate definitions for usages in WordNet, the `generate_t5.py` script does that.

**Comment by MengXu0826** [comment]
> Hi! What exactly is your aim? To produce cluster labels / sense definitions, you first of all need **usage clusters**. WordNet does not contain any usage clusters. If you simply want to generate definitions for usages in WordNet, the `generate_t5.py` script does that.

Cluster labels are exactly what I need. So I need to annotate usage clusters like DWUG in order to continue experiments on other datasets?

**Comment by akutuzov** [comment]
If you need cluster labels, you need clusters themselves first, yes (whatever is the way you produce these clusters). 
As an example, you can just assign all your usages one and the same cluster label and then run `sense_labels.py` on this data. It will generate one label.
In our experiments with DWUGs, clusters were already existing as part of these DWUGs.

**Comment by MengXu0826** [comment]
Thanks!!!
