### ISSUE TITLE
FileNotFoundError when Running generate_t5.py (testdata/complete.tsv.gz ?)

### ISSUE THREAD

**Issue by JiyuanAn** [ltgoslo/definition_modeling#3]
Hello!
I am currently working with your project definition_modeling and encountered an issue when trying to run the `generate_t5.py` script. I followed the instructions in the README to prepare the test data, but I'm facing a FileNotFoundError.

### Issue Description
While running the command:
```
python3 code/modeling/generate_t5.py --model ltg/flan-t5-definition-en-base --testdata testdata
```
I encountered the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'testdata/complete.tsv.gz'
```
According to the README, I have compressed `test.txt` and `test.eg` using gzip and placed them in the `./testdata` directory. However, it seems like the script is looking for a file named `complete.tsv.gz`. 

### My Understanding
Based on my understanding of the code, the content of the `testdata` file might be structured as follows:
```
word    example
vigilance    vigilance is especially susceptible to fatigue.
......
```

### Questions
1. Could you please provide the expected structure for the `complete.tsv` file?
2. How and where are `test.txt` and `test.eg` used in the script?

Any guidance or clarification you can provide would be greatly appreciated, as I am eager to properly utilize your project.

Thank you for your time and assistance. Thank you again for such excellent research.

Best regards,

**Comment by akutuzov** [comment]
Hi,
The data loading is performed differently, depending on what is the source of your data (see the [load_data()](https://github.com/ltgoslo/definition_modeling/blob/main/code/modeling/generate_t5.py#L13) function).

In short, it checks whether the path to the data includes the strings "oxford" or "wordnet". If it does, then the code looks for `*.eg.gz` and `*.txt.gz` files (they are used in the Oxford and Wordnet datasets). If it doesn't, the code looks for the `*.complete.tsv.gz` file, in the format used in the CoDWoE dataset.

Judging from your description, you want to process Oxford or Wordnet datasets. Then you should put them in a directory which includes "oxford" or "wordnet" in the path to it.

Hope this helps!

P.S. Yes, this is a rather quick and dirty way to define data processing routines. I am sorry for that :)

**Comment by jacklanda** [comment]
> Hi, The data loading is performed differently, depending on what is the source of your data (see the [load_data()](https://github.com/ltgoslo/definition_modeling/blob/main/code/modeling/generate_t5.py#L13) function).
> 
> In short, it checks whether the path to the data includes the strings "oxford" or "wordnet". If it does, then the code looks for `*.eg.gz` and `*.txt.gz` files (they are used in the Oxford and Wordnet datasets). If it doesn't, the code looks for the `*.complete.tsv.gz` file, in the format used in the CoDWoE dataset.
> 
> Judging from your description, you want to process Oxford or Wordnet datasets. Then you should put them in a directory which includes "oxford" or "wordnet" in the path to it.
> 
> Hope this helps!
> 
> P.S. Yes, this is a rather quick and dirty way to define data processing routines. I am sorry for that :)

In fact, there is not any file named with the suffix like `.eg.gz` or `.txt.gz`, according to the unzipped file from the naacl2019. Only `.eg` and `.txt` exist after decompressing the file.

Hence, I guess it is necessary to modify the code manually to adapt the correct data file path.

**Comment by akutuzov** [comment]
@jacklanda 
> In fact, there is not any file named with the suffix like `.eg.gz` or `.txt.gz`, according to the unzipped file from the naacl2019. Only `.eg` and `.txt` exist after decompressing the file.

In our pipeline,  we gzipped the Oxford and Wordnet dataset files, since it did not make sense to store them uncompressed and waste storage space (but we still wanted them to consist of separate files, not one huge `zip` archive).

Simply gzip these `.eg` and `.txt` file, and then no need to adapt anything in the code.

Of course, feel free to come up with a PR to improve our data loading pipeline, as I've said, it's quite hacky now :-)
