### ISSUE TITLE
embed_definitions.py missing

### ISSUE THREAD

**Issue by yvesscherrer** [ltgoslo/definition_modeling#4]
The DistilRoBERTa embeddings are supposed to be created with `code/embed_definitions.py` but there is only `code/embed_definitions_tfidf.py` which uses TF-IDF and not DistilRoBERTa. Do you happen to have the original file somewhere?

**Comment by glnmario** [comment]
It's in the proto_explanations folder: [code/proto_explanations/embed_definitions.py](https://github.com/ltgoslo/definition_modeling/blob/main/code/proto_explanations/embed_definitions.py)

But thanks for making us notice it's not very visible there :)

**Comment by yvesscherrer** [comment]
Ah thanks for the pointer, I didn't look hard enough ;)
